version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${PORT}:${PORT}'
    expose:
      - '${PORT}'
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ./redis:/data
